name: PyLint

on: push

jobs:

  PEP8:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python lint libraries
        run: pip install autopep8 autoflake isort black

      - name: Check for showstoppers
        run: |
          autopep8 --verbose --in-place --recursive --aggressive --aggressive assistant/*
          autopep8 --verbose --in-place --recursive --aggressive --aggressive plugins/*
          autopep8 --verbose --in-place --recursive --aggressive --aggressive vcbot/*

      - name: Remove unused imports and variables
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports assistant/*
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports plugins/*
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports vcbot/*

      - name: lint with isort and black
        run: |
          isort assistant/*
          black assistant/*
          isort plugins/*
          black plugins/*
          isort vcbot/*
          black vcbot/*

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'pylint: auto fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: buddhhu
          commit_user_email: 48654350+buddhhu@users.noreply.github.com
          commit_author: Amit Sharma <48654350+buddhhu@users.noreply.github.com>
          
