name: replace

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "new_thumb.jpg"

          replace: "ultroid.jpg"


      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Trying To Reduce 1 More var'

          commit_options: '--no-verify'

          repository: plugins


          commit_user_name: Danish
          commit_user_email: danish@ultroid.tech
          commit_author: Danish <danish@ultroid.tech>
