name: Strings Analysis

on:
  push:
    branches: dev
    paths: strings/strings/*
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    name: Some Naam
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - name: Install Stuff
        run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt install wget -y && pip install pyyaml requests
      - name: dl stuff
        run: wget -O stringizer.py https://gist.githubusercontent.com/New-dev0/6dfc8a177418565a776167764b2fe0e4/raw/ea831cf89ada2eab2939b4ff558a173e08a28f2e/stringzer.py
      - name: do stuff
        run: python stringizer.py && rm stringizer.py && wget -O run.py https://gist.githubusercontent.com/New-dev0/838fd1c51ca341723d6ab118c699d9f7/raw/3b384fb50563772c5229fbd1f4e021b005887923/reMainString.py && python run.py && rm run.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Strings: auto count'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: aviskumar
          commit_user_email: 85635883+aviskumar@users.noreply.github.com
          commit_author: Avish Kumar <85635883+aviskumar@users.noreply.github.com>
