name: Replacer
on: workflow_dispatch
jobs:
  Replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '"`Ooo Animated Sticker ðŸ‘€...`"'
          replace: "get_string('sts_9')"
          exclude: ['strings/', ".gi*]
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Replacer OP'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: ProgrammingError
          commit_user_email: error@notavailable.live
          commit_author: ProgrammingError <error@notavailable.live>
